### ISSUE TITLE
[BUG]:changing color on post when you are during clicking.

### ISSUE THREAD

**Issue by Raushankumar-prog** [Raushankumar-prog/Zealblog#1]
**Describe the bug**
when you start clicking on the post , it changes the color.

**To reproduce**
Just try to  click on the post , its color will changed into red.

**Expected behavior**
It should not change the color.

**Screenshots**

![Screenshot 2023-12-16 063316](https://github.com/Raushankumar-prog/Zealblog/assets/119419311/5735249d-a686-4277-825d-23295c2bf317)

![Screenshot 2023-12-16 063552](https://github.com/Raushankumar-prog/Zealblog/assets/119419311/9e2dd775-6a30-4730-83c8-592483c05cd1)

**Comment by Raushankumar-prog** [comment]
<table style="width:100%; border:1px solid black;">
  <tr>
    <th style="border:1px solid black;">Company</th>
    <th style="border:1px solid black;">Contact</th>
    <th style="border:1px solid black;">Country</th>
  </tr>
  <tr>
    <td style="border:1px solid black;">Alfreds Futterkiste</td>
    <td style="border:1px solid black;">Maria Anders</td>
    <td style="border:1px solid black;">Germany</td>
  </tr>
  <tr>
    <td style="border:1px solid black;">Centro comercial Moctezuma</td>
    <td style="border:1px solid black;">Francisco Chang</td>
    <td style="border:1px solid black;">Mexico</td>
  </tr>
</table>

**Comment by Raushankumar-prog** [comment]
<table style="width:100%; border:1px solid black;">
  <tr>
    <th >Company</th>
    <th >Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td >Alfreds Futterkiste</td>
    <td style="border:1px solid black;">Maria Anders</td>
    <td style="border:1px solid black;">Germany</td>
  </tr>
  <tr>
    <td style="border:1px solid black;">Centro comercial Moctezuma</td>
    <td style="border:1px solid black;">Francisco Chang</td>
    <td style="border:1px solid black;">Mexico</td>
  </tr>
</table>

**Comment by Raushankumar-prog** [comment]
<table style="border: 1px solid black; padding: 8px;">
      <thead>
        <tr>
          <th>Company</th>
          <th>Contact</th>
          <th>Country</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Alfreds Futterkiste</td>
          <td>Maria Anders</td>
          <td>Germany</td>
        </tr>
        <tr>
          <td>Centro comercial Moctezuma</td>
          <td>Francisco Chang</td>
          <td>Mexico</td>
        </tr>
      </tbody>
    </table>

**Comment by oranjan** [comment]
Hi, can I work on this ?

**Comment by Raushankumar-prog** [comment]
Hi @oranjan, I  am working this bug.
